apiVersion: v1
kind: ConfigMap
metadata:
        name: redmine-config
        namespace: redmine
        labels:
                tier: frontend
data:
        REDMINE_DB_POSTGRES: database.database
        REDMINE_DB_HOST: database.database
        REDMINE_DB_PORT: "5432"
        REDMINE_DB_DATABASE: redmine
        
