apiVersion: v1
kind: Service
metadata:
        name: redmine
        namespace: redmine
        labels:
                tier: frontend
spec:
        selector:
                tier: frontend
        ports:
        - protocol: "TCP"
          port: 80
          targetPort: 3000
        type: LoadBalancer
