apiVersion: v1
kind: Secret
metadata:
        name: database-secrets
        namespace: database
        labels:
                tier: backend
stringData:
        POSTGRES_USER: redmine
        POSTGRES_PASSWORD: redmine
     
