apiVersion: v1
appVersion: 2.16.0
description: Prometheus is a monitoring system and time series database.
engine: gotpl
home: https://prometheus.io/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- email: zanhsieh@gmail.com
  name: zanhsieh
name: prometheus
dependencies:
- name: kube-state-metrics
  version: "2.7.*"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: kubeStateMetrics.enabled
- name: grafana
  version: "5.0.*"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: grafana.enabled  
sources:
- https://github.com/prometheus/alertmanager
- https://github.com/prometheus/prometheus
- https://github.com/prometheus/pushgateway
- https://github.com/prometheus/node_exporter
- https://github.com/kubernetes/kube-state-metrics
- https://github.com/grafana/grafana
tillerVersion: '>=2.8.0'
version: 11.1.2
